In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import os
import numpy as np
import random
import copy
import sys
import pygame
import random
from pygame import *
import numpy as np
from main import DinoGameEnv
import matplotlib.pyplot as plt
from agent import Agent
from model import Model
from collections import deque
%matplotlib inline

# device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device = torch.device('cpu')
device

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html


device(type='cpu')

In [2]:
os.chdir('/home/sans/Music/DinoAI')

In [3]:
env = DinoGameEnv()

In [5]:
env = DinoGameEnv()
states = env.reset()
env.allow_rendering = True
scores = 0
for i in range(10):
    action = np.random.choice(np.arange(0,4))
    S_, R, done = env.step(action)
    print(S_)
    scores += R
    
    if done:
        print('Max scores: ', scores)
        states = env.reset()
        scores = 0
        
    if i == 9:
        env.close()
        break

[ 1. 23. 25.  0.  1.]
[ 1. 16. 25.  0.  1.]
[ 1. 10. 25.  0.  1.]
[ 1. 10. 25.  0.  1.]
[ 1. 10. 25.  0.  1.]
[ 1.  3. 25.  0.  1.]
[ 1.  3. 25.  0.  1.]
[ 1.  2. 25.  0.  0.]
[ 1. 25. 25.  0.  0.]
[ 1. 15. 25.  0.  0.]


In [4]:
agent = Agent(5, 2)
agent.epsilon = 1.0

In [6]:
def dqn():
    scores_deque = deque(maxlen=100)
    scores = []
    n_episodes = 5000
    env.allow_rendering = True
    i = 1
    for episode in range(n_episodes):
        state = env.reset()
        done = False
        score = 0
        while not done:
            action = agent.act(state)
#             print(action)
#             action = np.random.choice(np.arange(0,4))
            new_state, reward, done = env.step(action)
            agent.step(state, action, reward, new_state, done)
            state = new_state
            score += reward
            if done:
                break
                
        scores_deque.append(score)
        scores.append(score)
        
        print('\rEpisode {}\tAverage Score: {:.2f}\tReward: {}\t '.format(episode, np.mean(scores_deque), score), end="")
            
        if np.mean(scores_deque) > 50*i:
            print('Saving environment at scores {}'.format(np.mean(scores_deque)))
            torch.save(agent.local_nn.state_dict(), 'checkpoint' + '_update_' + str(50*i) + '.pth')
            
            i += 1
        if np.mean(scores_deque)>=1000.0:
            print('\nEnvironment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(episode, np.mean(scores_deque)))
            torch.save(agent.local_nn.state_dict(), 'checkpoint.pth')
            break
            
    return scores
            

In [7]:
total_scores = dqn()

Episode 39	Average Score: 67.33	Reward: 1510	 Saving environment at scores 67.325
Episode 40	Average Score: 101.12	Reward: 1453	 Saving environment at scores 101.1219512195122
Episode 49	Average Score: 167.02	Reward: 2115	 Saving environment at scores 167.02
Episode 62	Average Score: 214.68	Reward: 1860	 Saving environment at scores 214.68253968253967
Episode 67	Average Score: 252.43	Reward: 1845	 Saving environment at scores 252.4264705882353
Episode 71	Average Score: 304.46	Reward: 2989	 Saving environment at scores 304.4583333333333
Episode 83	Average Score: 359.20	Reward: 1597	 Saving environment at scores 359.20238095238096
Episode 89	Average Score: 416.80	Reward: 2658	 Saving environment at scores 416.8
Episode 95	Average Score: 463.58	Reward: 2661	 Saving environment at scores 463.5833333333333
Episode 101	Average Score: 511.41	Reward: 2081	 Saving environment at scores 511.41
Episode 108	Average Score: 559.14	Reward: 1746	 Saving environment at scores 559.14
Episode 112	Average

KeyboardInterrupt: 

In [12]:
agent.local_nn.load_state_dict(torch.load('checkpoint_400.pth'))

state = env.reset()
env.allow_rendering = True
score = 0
done = False
agent.local_nn.eval()
agent.epsilon = 0.005
agent.local_nn.eval()
while not done:
    action = agent.act(state)
    new_state, reward, done = env.step(action)
#     agent.step(state, action, reward, new_state, done)
    state = new_state
    score += reward
    if done:
        print(score)
        break
        

26


In [9]:
env.close()

In [ ]:
env.step(1)